---
swagger: "2.0"
info:
  version: "2022-07-18T17:19:03Z"
  title: "dev-product-service"
host: "70xhm5vprh.execute-api.eu-central-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /image/random:
    get:
      responses: {}
  /products:
    get:
      responses: {}
  /products/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses: {}
